### ISSUE TITLE
Looks like flags are not working

### ISSUE THREAD

**Issue by SBoudrias** [scottcorgan/nash#32]
Hey, we're considering using Nash for Yeoman.

I've started moving our cli file over, but it looks like global flags are not considered. Can this be related to the fact we use a default command?

I have a branch here: https://github.com/SBoudrias/yo/blob/nash/lib/cli.js (it is still WIP)

**Comment by SBoudrias** [comment]
Hey, are you sure it is working, I'm still unable to make it work with Yeoman. You can see and test against my branch here: https://github.com/SBoudrias/yo/tree/nash

**Comment by scottcorgan** [comment]
I'll run your code locally and find out what's going on.

* Are they just not running?
* Which flags? Global? Command specific?

**Comment by scottcorgan** [comment]
@SBoudrias scratch those last questions, I found the issue.

https://github.com/SBoudrias/yo/blob/nash/lib/cli.js#L122 should be:

```
cli.run(process.argv)
```

No need to slice out the first two items of the array.

**Comment by SBoudrias** [comment]
Oh, great thanks

Mind if I drop another question here, for Yeoman, we have basically two type of help:

`yo --help` which print global help  
`yo angular --help` which print a specific generator help

As the generator name is an unknown variable, how would you handle this with nash?

**Comment by scottcorgan** [comment]
At this point, it's kind of up to how you'd like to handle. In pre `1.0` Nash, an automated help/usage screen was built it. I found this inflexible and worth pulling out.

I put the idea of plugins into nash for this very thing, and in fact, I'm working on a `nash-help` plugin that adds all sorts of help screen functionality when defining flags/commands. Things like `description()` and `hidden()` are added to the flags/commands definition, and `-h, --help` pull up this screen, either for all commands, or one specific command.

But, until then, here are some options:

1) Access the parsed argv on the cli object. Uses [minimist](https://github.com/substack/minimist).

```js
cli.flag('--help', '-h').handler(function () {
  
  var commandName = cli.argv._[1]; 

  // Do something with commandName

  // Note: this works if the -h flag is after the command name.
  // If the command name follows the -h flag, then the first argument
  // in the flag handler will be the command name (i.e. yo -h angular vs. yo angular -h)
  // This is a minimist parsing thing
});
```

2) [Override](https://github.com/scottcorgan/nash#override) the global help flag with a command-level flag

```js

var angularCommand = cli.command('angular')
  .handler(function () {
  });

angularCommand.flag('--help', '-h')
  .override()
  .handler(function () {
  });

```

I am open to suggestions. Maybe a new issue warrants this.
