### ISSUE TITLE
DISCUSSION: removing options for sync/async and defaulting to async

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/nash#39]
Im interested in whether the `async()` method on flags and commands is actually helpful. It seems that most commands from the command line are sync, but I'm tempted to deprecate that option in favor of assuming everything wants async.

This would mean ever handler (flag or command) would receive a next/done callback function that would need to be called in order to proceed in execution.

Is this something worth assuming, or should this type of flexibility be left in?

- [x] wrappers
- [x] flag
- [x] flags
- [x] command
- [x] commands
- [x] plugins
- [x] cli

**Comment by fnky** [comment]
It would be a great in cases where you use `register` as a way of making sure the issued command proceeds or not.

**Comment by scottcorgan** [comment]
Agreed. Are you suggesting that `register()` should have a callback as well and be run async?

**Comment by fnky** [comment]
That's a good question as `register()` already seems to be very middleware-like, although you have to export `.register` rather than `module.exports`.

**Comment by scottcorgan** [comment]
A framework like Hapi does have a callback when registering plugins. So, if we go all async, all around, then I think that `register()` should also be async.

**Comment by fnky** [comment]
Totally agree. Keep everything async keeps it normalized throughout the API and most people expect this anyway nowadays.
