### ISSUE TITLE
Run a command by name

### ISSUE THREAD

**Issue by fnky** [scottcorgan/nash#47]
It would be nice with a way to easily run a command by passing a `String` to `run()`. Proposed API:

    cli.run(command[, argv]);

- **command** `String` - The name of command to run.
- **argv** `Array` - Arguments/flags passed to the command

Which will run any registered command, like so:

```js
cli.command('help').handler(function (cmd) { /**/ });
```

and then run the `help` command like this:

```js
cli.run('help');
```

and could also run the command with other args

```js
cli.run('help', ['mycommand']);
```

would be helpful in cases, where you use `default()`:

```js
cli.default().handler(function(flags) {
  if(flags[0] === undefined) {
    cli.run('help');
    return;
  }
  cli.run('help', flags.shift());
});
```

This makes it easier to run commands without explicitly running `cli.run` with the usual `['', '', ...]` syntax by nature.

**Comment by scottcorgan** [comment]
Would you be opposed to `cli.runCommand('help', ['options'])`?

Really wanted to keep the `run()` function doing run thing, namely running the cli instance.

**Comment by fnky** [comment]
Sure, however in my opinion, reusing `run` makes more sense than having two "run" methods. But it would make it easier to implement, of course :-)

**Comment by scottcorgan** [comment]
I'm going to think about this as I work on `2.0`. Keep me posted with any more ideas you have. I like this one.

**Comment by scottcorgan** [comment]
@fnky by the way, can do this right now with:

```js
cli.command('command-name').run([data], {/* flags */}, function (err) {

});
```

Forgot that was already built in. Does that suit your needs?

**Comment by scottcorgan** [comment]
I'm going to go head and close this. I know that Nash `3.0` will have some significant changes to how data is passed to handlers, so the function signature will change, but the rest will stay the same.

This seems like the most straight forward way to run a command. Plus, this allows us to do other things with the command.
